services:
  java-backend:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - python-microservice
    volumes:
      - ./audios:/app/audios

  python-microservice:
    build:
      context: ./WhisperTranscriptor
    ports:
      - "8000:8000"